### ISSUE TITLE
https://vvv.test Working on FIrefox but not working in Chrome

### ISSUE THREAD

**Issue by debabratakarfa** [Varying-Vagrant-Vagrants/VVV#2013]
https://vvv.test - When I try to access from Google chrome this error,

> Your connection is not private
Attackers might be trying to steal your information from vvv.test (for example, passwords, messages or credit cards). Learn more
NET::ERR_CERT_REVOKED

> Help improve Chrome security by sending URLs of some pages that you visit, limited system information and some page content to Google. Privacy Policy
vvv.test normally uses encryption to protect your information. When Google Chrome tried to connect to vvv.test this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be vvv.test, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Google Chrome stopped the connection before any data was exchanged.

> You cannot visit vvv.test right now because its certificate has been revoked. Network errors and attacks are usually temporary, so this page will probably work later.

But it working fine with Firefox.

I follow instructions from this https://varyingvagrantvagrants.org/docs/en-US/references/https/trusting-ca/

**Comment by debabratakarfa** [comment]
Same behavior in Microsoft Edge too, I think any browser using Keychain certificates not working.

**Comment by Mte90** [comment]
Seems a problems with certificates, did you followed the instructions for windows 10?

**Comment by tomjn** [comment]
Didn’t we have an issue recently with this exact issue that got resolved? I
don’t know how you managed to revoke the certificate as that isn’t VVV
itself would do, but destroy the certificates folder, reprovision, and
re-follow the steps

**Comment by tomjn** [comment]
I believe this is the cause:

https://stackoverflow.com/questions/34364459/neterr-cert-revoked-in-chrome-when-the-certificate-is-not-actually-revoked

> The first part of the question has been answered below. The reason why the site stopped working recently is b/c Google decided to distrust the “Class 3 Public Primary CA” root certificate, as explained here: https://googleonlinesecurity.blogspot.ca/2015/12/proactive-measures-in-digital.html

> 
> and here: https://code.google.com/p/chromium/issues/detail?id=570892
> 
> Since the decision was reversed for now, the problem can be fixed by getting the latest CRLSet in chrome://components/


the fix:

> First, the good news is the change has been temporarily reverted, and you should find access restored. You can force an update by going to chrome://components and under CRLSet, clicking "Update". You should have version 2698 or later to fix this issue.

**Comment by debabratakarfa** [comment]
https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2013#issuecomment-560368460

I did but not worked.

**Comment by debabratakarfa** [comment]
<img width="858" alt="Screenshot 2019-12-05 13 54 53" src="https://user-images.githubusercontent.com/2614495/70217331-f4d62780-1766-11ea-9fbc-addd51fb9937.png">

I wish if the ticket reopens again.

**Comment by debabratakarfa** [comment]
config
```
  wordpress-two:
    skip_provisioning: false
    description: "A standard WP install, useful for building plugins, testing things, etc"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    custom:
      locale: it_IT
      delete_default_plugins: true
      install_plugins:
        - query-monitor
    hosts:
      - two.wordpress.test
```

It choosing name rather than the hosts

**Comment by Mte90** [comment]
> Seems a problems with certificates, did you followed the instructions for windows 10?

Did you tried this?
We can reopen if you can confirm, it is a problem of certificates in your machine. 
Can you try with a vagrant provision? We did some changes to the vvv-utilities in this days.

**Comment by tomjn** [comment]
That’s an unrelated issue and one I believe I fixed last night

**Comment by tomjn** [comment]
The TLDR update your utilities by reprovisioning after clearing out your
certificates folder. You can keep the default and CA folders intact

**Comment by debabratakarfa** [comment]
Thanks @tomjn 
Do I need to checkout develop branch and pull and then run `vagrant reload --provision` ?

**Comment by tomjn** [comment]
A reprovision should do the trick

**Comment by debabratakarfa** [comment]
I run this command

```
git fetch origin develop
git reset --hard origin/develop
// then delete the certificate folder
vagrant reload --provision
```

No benefit, still the same issue.

<img width="738" alt="Screenshot 2019-12-09 13 05 44" src="https://user-images.githubusercontent.com/2614495/70416233-9d94c780-1a84-11ea-929b-264582992c86.png">

**Comment by debabratakarfa** [comment]
<img width="621" alt="Screenshot 2019-12-09 13 19 08" src="https://user-images.githubusercontent.com/2614495/70417101-8525ac80-1a86-11ea-8d15-c773e0d498de.png">

**Comment by debabratakarfa** [comment]
Refer: 

1. https://support.apple.com/en-us/HT210176
2. https://superuser.com/questions/1492207/neterr-cert-revoked-in-chrome-chromium-introduced-with-macos-catalina

**Comment by debabratakarfa** [comment]
<img width="1223" alt="Screenshot 2019-12-09 13 29 56" src="https://user-images.githubusercontent.com/2614495/70417779-ffa2fc00-1a87-11ea-9db6-1334870cb46b.png">

**Comment by Mte90** [comment]
As written on https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2013#issuecomment-563104387
Did you removed your certificate before the provision?

**Comment by debabratakarfa** [comment]
Yea I did.

**Comment by Mte90** [comment]
I am on Linux and I don't have this problem with Chromium or Firefox. 
We need someone with Windows that can help on understand the issue but seems mainly an issue of Chromium that is not our fault because the certificate is valid for everyone but Chrome changed the policy so is not possible to use anymore autosigned certificates.

**Comment by debabratakarfa** [comment]
I am using MacOs Catalina v 10.15.1

**Comment by tomjn** [comment]
@debabratakarfa I can confirm the certificates don't work on Safari, but would note a few things:

1. This is unrelated to the original issue, and has nothing to do with the certificate revokation issue in Chrome encountered earlier
2. The BAD CERT DOMAIN is also an unrelated separate issue that was introduced by fixes for Codacy issues, that was resolved in a PR that got merged
3. Making VVV certificates work with Catalina isn't a quick fix, and I don't have an estimate on how long it will take
4. If you read the details safari gives you there's a link to bypass this warning and explicitly trust the site, so this is not a blocker to doing development work

**Comment by debabratakarfa** [comment]
Hi @tomjn 

1. Yes development is block for Safari and as well as Firefox.
2. Block on Google Chrome, which is great for debugging.

Thank you for your update. Hope you able to fix, the Catalina issue. Thx

**Comment by tomjn** [comment]
I believe it's these latter 2 items that are tripping up Catalina:

 - TLS server certificates must contain an ExtendedKeyUsage (EKU) extension containing the id-kp-serverAuth OID.
 - TLS server certificates must have a validity period of 825 days or fewer (as expressed in the NotBefore and NotAfter fields of the certificate).

Our certificates last 3650 days/10 years, and there's no ExtendedKeyUsage extension

**Comment by debabratakarfa** [comment]
Yes @tomjn,
I was trying to found why it is not working then I found this, https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2013#issuecomment-563111741

**Comment by debabratakarfa** [comment]
Ansible fixed by changing the years, https://github.com/ansible/ansible/pull/64563/files

**Comment by tomjn** [comment]
@debabratakarfa latest version should now set it to 200 days, there's a follow up PR https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/pull/50 that should also improve things

**Comment by debabratakarfa** [comment]
Thank you @tomjn :)

**Comment by debabratakarfa** [comment]
Hi @tomjn 
Thank for the PR and it is working now. 🎉 
Thank you
