### ISSUE TITLE
Bug: Composer provisioner seems to be partially failing

### ISSUE THREAD

**Issue by ssnepenthe** [Varying-Vagrant-Vagrants/VVV#2573]
## What was The Command Used To Provision

```shell
vagrant up
```

## What Kind of VVV Provision Was This

This was a fresh install

## Logs/What Broke

Not really sure what to do with this - It has happened twice in a row.

Composer is successfully installed to /home/vagrant and given execute permission.

It seems like the provisioner is failing while trying to change ownership of files in /usr/local/bin. Nothing after this line in the provisioner function is running.

## Steps to Reproduce (for bugs)
1. New windows machine
2. Install virtualbox, vagrant and git
3. Open git bash as admin
4. Clone vvv, install plugins and run vagrant up
5. ???

Provisioning output: https://gist.github.com/ssnepenthe/5efa946668b900ba4808e7cbe98dbf21

## Your Environment

Operating System: Windows 11
Vagrant Version: 2.2.19
Virtualbox Version: 6.1.32

**Comment by tomjn** [comment]
@ssnepenthe can you be more specific? I've tried looking through the logs but the only clue i have is `composer` and I could not find the problem output or the issue you described. When you say it's failing, how is it failing and where is it failing? Which provisioner function are you referring to?

**Comment by ssnepenthe** [comment]
Yeah sorry about that... I was referring to this: https://github.com/Varying-Vagrant-Vagrants/VVV/blob/dc28ec9fa53a4cab46d3857ce58cb2eeaec52f00/provision/core/composer/provision.sh

I did not see any errors or warnings, or really any indication that anything is wrong or failing.

However, once provisioning has finished if I run `vagrant ssh` and try to use composer I get `-bash: composer: command not found`.

When I look through that provisioner file it seems to be succeeding up through line 21. Composer is installed at /home/vagrant/composer.phar and has been given execute permissions. Nothing after that seems to have run.

For example I would assume that we should see more about composer in the ouput log such as "Composer installer steps completed" and "Making sure the Composer cache is not owned by root" but these entries are missing.

**Comment by tomjn** [comment]
So `/usr/local/bin/composer` does not exist? Or it exists but isn't in path?

**Comment by tomjn** [comment]
Does this PR result in more information? https://github.com/Varying-Vagrant-Vagrants/VVV/pull/2574

**Comment by ssnepenthe** [comment]
`/usr/local/bin/composer` does not exist.

> I'm not sure you've stated the actual problem

That's fair... Sorry if I haven't been very clear or helpful I'm just not really sure I know how else to approach this issue beyond "it doesn't seem to be working as expected..."

I am re-provisioning now with that PR and will get back to you.

**Comment by ssnepenthe** [comment]
```
   default:  ▷ Running the 'tools' provisioner...
    default:  * Running tools_install
    default:  ▷ Running tools_setup hook
    default:    - Starting subhook composer_setup with priority 10
    default:    - Starting subhook grunt_setup with priority 10
    default:  * Turning off XDebug to avoid Composer performance issues
    default:    - Starting subhook wp_cli_setup with priority 10
    default:  * Installing/updating WP-CLI
    default:  * Updating wp-cli...
    default: Error: /usr/local/bin is not writable by current user.
    default:  * Restarting PHP FPM services so that the change takes effect
    default:  ✔ All PHP Debug mods are now turned off.
    default:  * Checking if Composer is installed
    default:  * Running Composer Installer...
    default:  * Updating Grunt CLI
    default: /srv/provision/core/composer/provision.sh: line 21: -f: command not found
    default:  ! Expected to find a composer.phar after running composer installer, but none was found
    default:  * Updating grunt-sass
    default:  * starting gyphack loop
    default:  * grunt-sass Updated
    default:  * Updating grun-cssjanus and grunt-rtlcss
    default:  * Stopped gyphack loop
    default:  * Completed Grunt CLI update
    default:    - Subhooks completed for tools_setup with priority 10
    default:  ✔ Finished tools_setup hook in 10s
    default:  ▷ Running tools_setup_synchronous hook
    default:  * Finalizing Tools
    default:  ✔ The 'tools' provisioner completed in 10 seconds.
```

**Comment by ssnepenthe** [comment]
The contents of the actual log file at `log/provisioners/{time}/provisioner-tools.log` appear to include some additional output from the composer installer script indicating that composer was successfully installed...

```
[0;38;5;2m ▷ Running the [0m[1m[0;38;5;5m'tools'[21m[0;38;5;2m provisioner...[0m[0m[0m
[0m[39m[2m * Running tools_install[21m[0m
[0m[39m[2m ▷ Running [0m[1m[0;38;5;5mtools_setup[21m[0m[39m[2m hook[21m[0m
[0m[39m[2m   - Starting subhook composer_setup with priority 10[21m[0m
[0m[39m[2m * Turning off XDebug to avoid Composer performance issues[21m[0m
[0m[39m[2m   - Starting subhook grunt_setup with priority 10[21m[0m
[0m[39m[2m   - Starting subhook wp_cli_setup with priority 10[21m[0m
[0m[39m[2m * Installing/updating WP-CLI[21m[0m
[0m[39m[2m * Updating wp-cli...[21m[0m
[0m[39m[2m * Restarting PHP FPM services so that the change takes effect[21m[0m
Error: /usr/local/bin is not writable by current user.
[0;38;5;2m ✔ All PHP Debug mods are now turned off.[0m[0m
[0m[39m[2m * Checking if Composer is installed[21m[0m
[0m[39m[2m * Running Composer Installer...[21m[0m
All settings correct for using Composer
Downloading...
[0m[39m[2m * Updating Grunt CLI[21m[0m

Composer (version 2.2.5) successfully installed to: /home/vagrant/composer.phar
Use it: php composer.phar

/srv/provision/core/composer/provision.sh: line 21: -f: command not found
[0;38;5;9m ! Expected to find a composer.phar after running composer installer, but none was found[0m[0m
[0m[39m[2m * Updating grunt-sass[21m[0m
[0m[39m[2m * starting gyphack loop[21m[0m
[0m[39m[2m * grunt-sass Updated[21m[0m
[0m[39m[2m * Updating grun-cssjanus and grunt-rtlcss[21m[0m
[0m[39m[2m * Stopped gyphack loop[21m[0m
[0;38;5;2m * Completed Grunt CLI update[0m[0m
[0m[39m[2m   - Subhooks completed for tools_setup with priority 10[21m[0m
[0;38;5;2m ✔ Finished [0m[1m[0;38;5;5mtools_setup[21m[0;38;5;2m hook in [0m[0m[1m[0;38;5;5m8s[21m[0m[0m
[0m[39m[2m ▷ Running [0m[1m[0;38;5;5mtools_setup_synchronous[21m[0m[39m[2m hook[21m[0m
[0m[39m[2m * Finalizing Tools[21m[0m
[0;38;5;2m ✔ The [0m[1m[0;38;5;5m'tools'[21m[0;38;5;2m provisioner completed in [0m[0m[1m[0;38;5;5m9[21m[0;38;5;2m seconds.[0m[0m[0m
```

**Comment by tomjn** [comment]
looks like I forgot to wrap it in square brackets. I notice WP CLI updating has issues though. I've committed a fix for the `[]` to that branch

**Comment by tomjn** [comment]
As for the composer installer, it's just figuring out downloading `composer.phar`, it's the provisioner that then moves it into place

**Comment by tomjn** [comment]
I've also changed the move command to report if that failed or not

**Comment by ssnepenthe** [comment]
Interesting... I've now re-provisioned three times with the latest from #2574 with slightly different results each time. Relevant output from the three runs is below.

The first time the issue was still occurring.

The second time composer was installed correctly. It also seems to be correctly checking for github tokens and composer updates.

The third time composer was installed correctly again but there is nothing about github tokens or composer updates.

FIRST:

```
    default:  ▷ Running the 'tools' provisioner...
    default:  * Running tools_install
    default:  ▷ Running tools_setup hook
    default:    - Starting subhook composer_setup with priority 10
    default:  * Turning off XDebug to avoid Composer performance issues
    default:    - Starting subhook grunt_setup with priority 10
    default:    - Starting subhook wp_cli_setup with priority 10
    default:  * Installing/updating WP-CLI
    default:  * Updating wp-cli...
    default:  * Updating Grunt CLI
    default:  * Restarting PHP FPM services so that the change takes effect
    default:  ✔ All PHP Debug mods are now turned off.
    default:  * Checking if Composer is installed
    default:  * Running Composer Installer...
    default:  * starting gyphack loop
    default:  * Updating grunt-sass
    default:  * WP CLI Nightly updated
    default:  * Disabling debug mods if present before running wp package installs
    default:  * Restarting PHP FPM services so that the change takes effect
    default:  ✔ All PHP Debug mods are now turned off.
    default:  * Updating WP packages
    default:  * WP package updates completed
    default:    - Subhooks completed for tools_setup with priority 10
    default:  ✔ Finished tools_setup hook in 4s
    default:  ▷ Running tools_setup_synchronous hook
    default:  * Finalizing Tools
    default:  ✔ The 'tools' provisioner completed in 4 seconds.
```

SECOND:

```
    default:  ▷ Running the 'tools' provisioner...
    default:  * Running tools_install
    default:  ▷ Running tools_setup hook
    default:    - Starting subhook composer_setup with priority 10
    default:  * Turning off XDebug to avoid Composer performance issues
    default:    - Starting subhook grunt_setup with priority 10
    default:    - Starting subhook wp_cli_setup with priority 10
    default:  * Installing/updating WP-CLI
    default:  * Updating wp-cli...
    default:  * Restarting PHP FPM services so that the change takes effect
    default:  ✔ All PHP Debug mods are now turned off.
    default:  * Checking if Composer is installed
    default:  * Running Composer Installer...
    default:  * Updating Grunt CLI
    default:  * Setting ownership and executable bit of composer...
    default:  * Moving composer into place...
    default:  * Composer installed to /usr/local/bin
    default:  * Making sure the Composer cache is not owned by root
    default:  * Checking for GitHub tokens
    default:  * Checking for Composer updates
    default:  ▷ Running after_composer hook
    default:  * Provisioning PHP_CodeSniffer (phpcs), see https://github.com/squizlabs/PHP_CodeSniffer
    default: Loading composer repositories with package information
    default: Updating dependencies
    default: Lock file operations: 6 installs, 0 updates, 0 removals
    default:   - Locking automattic/vipwpcs (2.3.3)
    default:   - Locking dealerdirect/phpcodesniffer-composer-installer (v0.7.1)
    default:   - Locking phpcompatibility/php-compatibility (9.3.5)
    default:   - Locking sirbrillig/phpcs-variable-analysis (v2.11.2)
    default:   - Locking squizlabs/php_codesniffer (3.6.2)
    default:   - Locking wp-coding-standards/wpcs (2.3.0)
    default: Writing lock file
    default: Installing dependencies from lock file (including require-dev)
    default: Package operations: 6 installs, 0 updates, 0 removals
    default:   - Downloading squizlabs/php_codesniffer (3.6.2)
    default:   - Downloading dealerdirect/phpcodesniffer-composer-installer (v0.7.1)
    default:   - Downloading wp-coding-standards/wpcs (2.3.0)
    default:  * starting gyphack loop
    default:  * Updating grunt-sass
    default:   - Downloading sirbrillig/phpcs-variable-analysis (v2.11.2)
    default:   - Downloading automattic/vipwpcs (2.3.3)
    default:   - Downloading phpcompatibility/php-compatibility (9.3.5)
    default:  * grunt-sass Updated
    default:  * Updating grun-cssjanus and grunt-rtlcss
    default:  * Stopped gyphack loop
    default:   - Installing squizlabs/php_codesniffer (3.6.2): Extracting archive
    default:  * WP CLI Nightly updated
    default:  * Disabling debug mods if present before running wp package installs
    default:  * Restarting PHP FPM services so that the change takes effect
    default:  ✔ All PHP Debug mods are now turned off.
    default:  * Updating WP packages
    default:  * Completed Grunt CLI update
    default:    - Subhooks completed for tools_setup with priority 10
    default:  ✔ Finished tools_setup hook in 21s
    default:  ▷ Running tools_setup_synchronous hook
    default:  * Finalizing Tools
    default:  ✔ The 'tools' provisioner completed in 21 seconds.
```

THIRD:

```
    default:  ▷ Running the 'tools' provisioner...
    default:  * Running tools_install
    default:  ▷ Running tools_setup hook
    default:    - Starting subhook composer_setup with priority 10
    default:  * Turning off XDebug to avoid Composer performance issues
    default:    - Starting subhook grunt_setup with priority 10
    default:    - Starting subhook wp_cli_setup with priority 10
    default:  * Installing/updating WP-CLI
    default:  * Updating wp-cli...
    default:  * Restarting PHP FPM services so that the change takes effect
    default:  ✔ All PHP Debug mods are now turned off.
    default:  * Checking if Composer is installed
    default:  * Running Composer Installer...
    default:  * Updating Grunt CLI
    default:  * WP CLI Nightly updated
    default:  * Disabling debug mods if present before running wp package installs
    default:  * Restarting PHP FPM services so that the change takes effect
    default:  ✔ All PHP Debug mods are now turned off.
    default:  * Updating WP packages
    default:  * Setting ownership and executable bit of composer...
    default:  * Moving composer into place...
    default:  * Composer installed to /usr/local/bin
    default:  * WP package updates completed
    default:  * Making sure the Composer cache is not owned by root
    default:    - Subhooks completed for tools_setup with priority 10
    default:  ✔ Finished tools_setup hook in 3s
    default:  ▷ Running tools_setup_synchronous hook
    default:  * Finalizing Tools
    default:  ✔ The 'tools' provisioner completed in 3 seconds.
```

**Comment by tomjn** [comment]
what do the log files say? Not everything gets printed to the terminal

**Comment by ssnepenthe** [comment]
FIRST:

```
[0;38;5;2m ▷ Running the [0m[1m[0;38;5;5m'tools'[21m[0;38;5;2m provisioner...[0m[0m[0m
[0m[39m[2m * Running tools_install[21m[0m
[0m[39m[2m ▷ Running [0m[1m[0;38;5;5mtools_setup[21m[0m[39m[2m hook[21m[0m
[0m[39m[2m   - Starting subhook composer_setup with priority 10[21m[0m
[0m[39m[2m * Turning off XDebug to avoid Composer performance issues[21m[0m
[0m[39m[2m   - Starting subhook grunt_setup with priority 10[21m[0m
[0m[39m[2m   - Starting subhook wp_cli_setup with priority 10[21m[0m
[0m[39m[2m * Installing/updating WP-CLI[21m[0m
[0m[39m[2m * Updating wp-cli...[21m[0m
[0m[39m[2m * Updating Grunt CLI[21m[0m
Downloading from https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli-nightly.phar...
[0m[39m[2m * Restarting PHP FPM services so that the change takes effect[21m[0m
[0;38;5;2m ✔ All PHP Debug mods are now turned off.[0m[0m
[0m[39m[2m * Checking if Composer is installed[21m[0m
[0m[39m[2m * Running Composer Installer...[21m[0m
All settings correct for using Composer
Downloading...
md5 hash verified: 95d62a48bf4ce749290078b62ebb4242
[0m[39m[2m * starting gyphack loop[21m[0m
[0m[39m[2m * Updating grunt-sass[21m[0m
New version works. Proceeding to replace.
Success: Updated WP-CLI to the latest nightly release.
[0;38;5;2m * WP CLI Nightly updated[0m[0m
[0m[39m[2m * Disabling debug mods if present before running wp package installs[21m[0m
[0m[39m[2m * Restarting PHP FPM services so that the change takes effect[21m[0m
[0;38;5;2m ✔ All PHP Debug mods are now turned off.[0m[0m
[0m[39m[2m * Updating WP packages[21m[0m
Using Composer to update packages...
---
Loading composer repositories with package information
Updating dependencies
Generating rules
Resolving dependencies through SAT
Looking at all rules.

Dependency resolution completed in 0.000 seconds
Analyzed 90 packages to resolve dependencies
Analyzed 90 rules to resolve dependencies
Nothing to modify in lock file
Installing dependencies from lock file
Nothing to install, update or remove
Generating autoload files
---
Success: Packages updated.
[0m[39m[2m * WP package updates completed[21m[0m
[0m[39m[2m   - Subhooks completed for tools_setup with priority 10[21m[0m
[0;38;5;2m ✔ Finished [0m[1m[0;38;5;5mtools_setup[21m[0;38;5;2m hook in [0m[0m[1m[0;38;5;5m4s[21m[0m[0m
[0m[39m[2m ▷ Running [0m[1m[0;38;5;5mtools_setup_synchronous[21m[0m[39m[2m hook[21m[0m
[0m[39m[2m * Finalizing Tools[21m[0m
[0;38;5;2m ✔ The [0m[1m[0;38;5;5m'tools'[21m[0;38;5;2m provisioner completed in [0m[0m[1m[0;38;5;5m4[21m[0;38;5;2m seconds.[0m[0m[0m

Composer (version 2.2.5) successfully installed to: /home/vagrant/composer.phar
Use it: php composer.phar
```

SECOND:

```
[0;38;5;2m ▷ Running the [0m[1m[0;38;5;5m'tools'[21m[0;38;5;2m provisioner...[0m[0m[0m
[0m[39m[2m * Running tools_install[21m[0m
[0m[39m[2m ▷ Running [0m[1m[0;38;5;5mtools_setup[21m[0m[39m[2m hook[21m[0m
[0m[39m[2m   - Starting subhook composer_setup with priority 10[21m[0m
[0m[39m[2m * Turning off XDebug to avoid Composer performance issues[21m[0m
[0m[39m[2m   - Starting subhook grunt_setup with priority 10[21m[0m
[0m[39m[2m   - Starting subhook wp_cli_setup with priority 10[21m[0m
[0m[39m[2m * Installing/updating WP-CLI[21m[0m
[0m[39m[2m * Updating wp-cli...[21m[0m
[0m[39m[2m * Restarting PHP FPM services so that the change takes effect[21m[0m
Downloading from https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli-nightly.phar...
[0;38;5;2m ✔ All PHP Debug mods are now turned off.[0m[0m
[0m[39m[2m * Checking if Composer is installed[21m[0m
[0m[39m[2m * Running Composer Installer...[21m[0m
All settings correct for using Composer
Downloading...
[0m[39m[2m * Updating Grunt CLI[21m[0m

Composer (version 2.2.5) successfully installed to: /home/vagrant/composer.phar
Use it: php composer.phar

[0m[39m[2m * Setting ownership and executable bit of composer...[21m[0m
[0m[39m[2m * Moving composer into place...[21m[0m
[0;38;5;2m * Composer installed to /usr/local/bin[0m[0m
[0m[39m[2m * Making sure the Composer cache is not owned by root[21m[0m
[0m[39m[2m * Checking for GitHub tokens[21m[0m
[0m[39m[2m * Checking for Composer updates[21m[0m
Composer version 2.2.5 2022-01-21 17:25:52
[0m[39m[2m ▷ Running [0m[1m[0;38;5;5mafter_composer[21m[0m[39m[2m hook[21m[0m
[0m[39m[2m * Provisioning PHP_CodeSniffer (phpcs), see https://github.com/squizlabs/PHP_CodeSniffer[21m[0m
Loading composer repositories with package information
Updating dependencies
Lock file operations: 6 installs, 0 updates, 0 removals
  - Locking automattic/vipwpcs (2.3.3)
  - Locking dealerdirect/phpcodesniffer-composer-installer (v0.7.1)
  - Locking phpcompatibility/php-compatibility (9.3.5)
  - Locking sirbrillig/phpcs-variable-analysis (v2.11.2)
  - Locking squizlabs/php_codesniffer (3.6.2)
  - Locking wp-coding-standards/wpcs (2.3.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 6 installs, 0 updates, 0 removals
  - Downloading squizlabs/php_codesniffer (3.6.2)
  - Downloading dealerdirect/phpcodesniffer-composer-installer (v0.7.1)
  - Downloading wp-coding-standards/wpcs (2.3.0)
[0m[39m[2m * starting gyphack loop[21m[0m
[0m[39m[2m * Updating grunt-sass[21m[0m
  - Downloading sirbrillig/phpcs-variable-analysis (v2.11.2)
  - Downloading automattic/vipwpcs (2.3.3)
  - Downloading phpcompatibility/php-compatibility (9.3.5)
[0m[39m[2m * grunt-sass Updated[21m[0m
[0m[39m[2m * Updating grun-cssjanus and grunt-rtlcss[21m[0m
[0m[39m[2m * Stopped gyphack loop[21m[0m
md5 hash verified: 95d62a48bf4ce749290078b62ebb4242
  - Installing squizlabs/php_codesniffer (3.6.2): Extracting archive
New version works. Proceeding to replace.
Success: Updated WP-CLI to the latest nightly release.
[0;38;5;2m * WP CLI Nightly updated[0m[0m
[0m[39m[2m * Disabling debug mods if present before running wp package installs[21m[0m
[0m[39m[2m * Restarting PHP FPM services so that the change takes effect[21m[0m
[0;38;5;2m ✔ All PHP Debug mods are now turned off.[0m[0m
[0m[39m[2m * Updating WP packages[21m[0m
Using Composer to update packages...
---
Loading composer repositories with package information
[0;38;5;2m * Completed Grunt CLI update[0m[0m
[0m[39m[2m   - Subhooks completed for tools_setup with priority 10[21m[0m
[0;38;5;2m ✔ Finished [0m[1m[0;38;5;5mtools_setup[21m[0;38;5;2m hook in [0m[0m[1m[0;38;5;5m21s[21m[0m[0m
[0m[39m[2m ▷ Running [0m[1m[0;38;5;5mtools_setup_synchronous[21m[0m[39m[2m hook[21m[0m
[0m[39m[2m * Finalizing Tools[21m[0m
[0;38;5;2m ✔ The [0m[1m[0;38;5;5m'tools'[21m[0;38;5;2m provisioner completed in [0m[0m[1m[0;38;5;5m21[21m[0;38;5;2m seconds.[0m[0m[0m
Updating dependencies
Generating rules
Resolving dependencies through SAT
Looking at all rules.

Dependency resolution completed in 0.000 seconds
Analyzed 90 packages to resolve dependencies
Analyzed 90 rules to resolve dependencies
Nothing to modify in lock file
Installing dependencies from lock file
Nothing to install, update or remove
Generating autoload files
---
Success: Packages updated.

Fatal error: Uncaught Symfony\Component\Console\Exception\RuntimeException: Unable to write output. in phar:///usr/local/bin/composer/vendor/symfony/console/Output/StreamOutput.php:79
Stack trace:
#0 phar:///usr/local/bin/composer/vendor/symfony/console/Output/Output.php(164): Symfony\Component\Console\Output\StreamOutput->doWrite()
#1 phar:///usr/local/bin/composer/vendor/symfony/console/Output/Output.php(132): Symfony\Component\Console\Output\Output->write()
#2 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(641): Symfony\Component\Console\Output\Output->writeln()
#3 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(127): Symfony\Component\Console\Application->renderException()
#4 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(131): Symfony\Component\Console\Application->run()
#5 phar:///usr/local/bin/composer/bin/composer(83): Composer\Console\Application->run()
#6 /usr/local/bin/composer(29): require('phar:///usr/loc...')
#7 {main}
  thrown in phar:///usr/local/bin/composer/vendor/symfony/console/Output/StreamOutput.php on line 79
```

THIRD:

```
[0;38;5;2m ▷ Running the [0m[1m[0;38;5;5m'tools'[21m[0;38;5;2m provisioner...[0m[0m[0m
[0m[39m[2m * Running tools_install[21m[0m
[0m[39m[2m ▷ Running [0m[1m[0;38;5;5mtools_setup[21m[0m[39m[2m hook[21m[0m
[0m[39m[2m   - Starting subhook composer_setup with priority 10[21m[0m
[0m[39m[2m * Turning off XDebug to avoid Composer performance issues[21m[0m
[0m[39m[2m   - Starting subhook grunt_setup with priority 10[21m[0m
[0m[39m[2m   - Starting subhook wp_cli_setup with priority 10[21m[0m
[0m[39m[2m * Installing/updating WP-CLI[21m[0m
[0m[39m[2m * Updating wp-cli...[21m[0m
[0m[39m[2m * Restarting PHP FPM services so that the change takes effect[21m[0m
Downloading from https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli-nightly.phar...
[0;38;5;2m ✔ All PHP Debug mods are now turned off.[0m[0m
[0m[39m[2m * Checking if Composer is installed[21m[0m
[0m[39m[2m * Running Composer Installer...[21m[0m
All settings correct for using Composer
Downloading...
[0m[39m[2m * Updating Grunt CLI[21m[0m
md5 hash verified: 95d62a48bf4ce749290078b62ebb4242
New version works. Proceeding to replace.
Success: Updated WP-CLI to the latest nightly release.
[0;38;5;2m * WP CLI Nightly updated[0m[0m
[0m[39m[2m * Disabling debug mods if present before running wp package installs[21m[0m
[0m[39m[2m * Restarting PHP FPM services so that the change takes effect[21m[0m
[0;38;5;2m ✔ All PHP Debug mods are now turned off.[0m[0m
[0m[39m[2m * Updating WP packages[21m[0m
Using Composer to update packages...
---
Loading composer repositories with package information

Composer (version 2.2.5) successfully installed to: /home/vagrant/composer.phar
Use it: php composer.phar

[0m[39m[2m * Setting ownership and executable bit of composer...[21m[0m
Updating dependencies
Generating rules
Resolving dependencies through SAT
Looking at all rules.

Dependency resolution completed in 0.001 seconds
Analyzed 90 packages to resolve dependencies
Analyzed 90 rules to resolve dependencies
Nothing to modify in lock file
Installing dependencies from lock file
Nothing to install, update or remove
Generating autoload files
[0m[39m[2m * Moving composer into place...[21m[0m
---
Success: Packages updated.
[0;38;5;2m * Composer installed to /usr/local/bin[0m[0m
[0m[39m[2m * WP package updates completed[21m[0m
[0m[39m[2m * Making sure the Composer cache is not owned by root[21m[0m
[0m[39m[2m   - Subhooks completed for tools_setup with priority 10[21m[0m
[0;38;5;2m ✔ Finished [0m[1m[0;38;5;5mtools_setup[21m[0;38;5;2m hook in [0m[0m[1m[0;38;5;5m3s[21m[0m[0m
[0m[39m[2m ▷ Running [0m[1m[0;38;5;5mtools_setup_synchronous[21m[0m[39m[2m hook[21m[0m
[0m[39m[2m * Finalizing Tools[21m[0m
[0;38;5;2m ✔ The [0m[1m[0;38;5;5m'tools'[21m[0;38;5;2m provisioner completed in [0m[0m[1m[0;38;5;5m3[21m[0;38;5;2m seconds.[0m[0m[0m
```

**Comment by tomjn** [comment]
@ssnepenthe I've made a number of improvements to logging etc, including better network checks. I've also moved the Grunt gyp loop hack out into a non-parallelised provisioner.

Can you check if things are improved on that PR?

**Comment by ssnepenthe** [comment]
Just tested the PR with a fresh provision and then a reprovision and everything seems to be working, thanks!

**Comment by tomjn** [comment]
@ssnepenthe now that it's been merged are we good to close this? I've created #2580 to handle the `npm` issue that was surfaced while looking into it as well as #2579 which will let us re-enable parallel hooks
