### ISSUE TITLE
The comamnd "vagrant ssh -c 'vagrant_up'" fails while doing `vagrant up`

### ISSUE THREAD

**Issue by sudar** [Varying-Vagrant-Vagrants/VVV#837]
I did a git pull recently and with the current master I am getting the following error while running the `vagrant up` command.

```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: A newer version of the box 'ubuntu/trusty64' is available! You currently
==> default: have version '20160201.0.0'. The latest is version '20160217.1.0'. Run
==> default: `vagrant box update` to update.
==> default: VirtualBox VM is already running.
==> default: Checking for host entries
==> default: Running triggers after up...
==> default: Executing command "vagrant ssh -c vagrant_up"...
==> default: bash: vagrant_up: command not found
==> default: Command execution finished.
The command "vagrant ssh -c 'vagrant_up'" returned a failed exit code. The
error output is shown below:

bash: vagrant_up: command not found
```

I did some debugging and found that this line was introduced in #782 

If I revert to master before this commit, then the `vagrant up` command works without any issues.

**Comment by mbootsman** [comment]
@sudar Having the same issue here.
How did you revert to the master before the commit?

**Comment by sudar** [comment]
@mbootsman I ran the following command in my vvv git repo directory

```
git checkout 53e2dcd
```

This is just a temporary fix till master is fixed. Once master if fixed, you may have to revert to master by using the following commands.

```
git checkout master
git pull origin master
```

**Comment by mbootsman** [comment]
@sudar Thanks, that did the trick :+1:

**Comment by cfoellmann** [comment]
Will Look into this this evening.
Did all of you install and/or reinstall the vagran triggers plugin?

**Comment by sudar** [comment]
@cfoellmann 

No. I didn't re-install vagrant trigger plugin.

The only change I did is to do a `git pull origin master` in the directory where I have checked out vvv and then did a `vagrant up`.

I didn't even do a provision.

**Comment by mbootsman** [comment]
@cfoellmann No, only did a `git pull origin master`. I do have the vagrant triggers plugin installed.

**Comment by pdewouters** [comment]
same issue for me

**Comment by jeremyfelt** [comment]
As the `vagrant_up` script is new to the configuration, it's possible that it is not in its proper location inside the VM yet. Does this persist after doing a `vagrant provision`?

**Comment by pdewouters** [comment]
yes, running `vagrat up --provision` fixes the issue for me. thanks

**Comment by mbootsman** [comment]
Problem solved with `vagrant up --provision`, thanks!

**Comment by jeremyfelt** [comment]
Excellent! :+1: 

For the next release we should note whether `vagrant provision` is required on upgrade.

**Comment by sudar** [comment]
I can also confirm that it works after doing a provision.

> For the next release we should note whether vagrant provision is required on upgrade.

Yes, please. This would have saved me some time.

**Comment by Pezzab** [comment]
Hello, I get the same error but provisioning didn't fix the problem. Everything is up to date (including Virtual Box).

**Comment by GaryJones** [comment]
@Pezzab I had the same too, but I ran `vagrant halt` first, then `vagrant up --provision` and the error didn't appear.

**Comment by techcoreJ** [comment]
Hi @cfoellmann
I get the same issue. I'm using **Vagrant 1.8.1** on the Mac OS X. I tried both **vagrant up** and **vagrant up --provision** but it's not solved. This is my log.

==> default: Running triggers after up...
==> default: Executing command "vagrant ssh -c vagrant_up"...
==> default: bash: vagrant_up: command not found
==> default: Command execution finished.
The local command "vagrant ssh -c 'vagrant_up'" returned a failed exit
code or an exception. The error output is shown below:

bash: vagrant_up: command not found

Regards,

**Comment by PenneyGadget** [comment]
@techcoreJ try just `vagrant provision` - that worked for me while the other two didn't.

**Comment by cfoellmann** [comment]
Check/reinstall the vagrant triggers plugin

**Comment by kingluddite** [comment]
Yes. `vagrant provision` worked for me. The others did not.
